namespace SoulBuddy.Services;

public sealed class LocationMapper
{
    private static readonly IReadOnlyDictionary<int, string> Locations =
        CreateLocations();

    public string? GetLocationName(int locationId)
    {
        return Locations.GetValueOrDefault(locationId);
    }

    private static IReadOnlyDictionary<int, string> CreateLocations()
    {
        var locations = new Dictionary<int, string>
        {
            [0] = "Mysteriöse Zone",
            [1] = "Zweiblattdorf",
            [2] = "Sandgemme",
            [3] = "Flori",
            [4] = "Trostu",
            [5] = "Elyses",
            [6] = "Jubelstadt",
            [7] = "Fleetburg",
            [8] = "Erzelingen",
            [9] = "Ewigenau",
            [10] = "Herzhofen",
            [11] = "Weideburg",
            [12] = "Schleiede",
            [13] = "Sonnewik",
            [14] = "Blizzach",
            [15] = "Pokémon-Liga",
            [46] = "Erzelingen-Mine",
            [47] = "Windkraftwerk",
            [48] = "Ewigwald",
            [49] = "Feuriohütte",
            [50] = "Kraterberg",
            [51] = "Speersäule",
            [52] = "Großmoor",
            [53] = "Trostu-Ruinen",
            [54] = "Siegesstraße (Sinnoh)",
            [55] = "Park der Freunde",
            [56] = "Platz der Treue",
            [57] = "Verwüsteter Pfad",
            [58] = "Auen von Flori",
            [59] = "Erzelingen-Tor",
            [60] = "Vollmond-Insel",
            [61] = "Scheidequelle",
            [62] = "Höhle der Umkehr",
            [63] = "Blumenparadies",
            [64] = "Blizzach-Tempel",
            [65] = "Bizarre Höhle",
            [66] = "Ruinenmaniac-Höhle",
            [67] = "Ruinenmaniac-Tunnel",
            [68] = "Trophäengarten",
            [69] = "Eiseninsel",
            [70] = "Alte Villa",
            [71] = "Galaktik-Zentrale",
            [72] = "Ufer des Wahrheitssees",
            [73] = "Kühnheitsufer",
            [74] = "Stärkeufer",
            [75] = "Frühlingspfad",
            [76] = "See der Wahrheit",
            [77] = "See der Kühnheit",
            [78] = "See der Stärke",
            [79] = "Neumond-Insel",
            [80] = "Duellturm",
            [81] = "Kampfareal",
            [82] = "Überlebensareal",
            [83] = "Erholungsgebiet",
            [84] = "Kahlberg",
            [85] = "Eichenpfad",
            [86] = "Halle des Beginns",
            [87] = "Wahrheitsgrotte",
            [88] = "Kühnheitsgrotte",
            [89] = "Stärkegrotte",
            [90] = "Jubelstadt TV",
            [91] = "Pokétch-Gesellschaft",
            [92] = "Global Trade Station",
            [93] = "Trainerschule",
            [94] = "Bergbaumuseum",
            [95] = "Blumenladen",
            [96] = "Fahrradladen",
            [97] = "Wettbewerbshalle",
            [98] = "Knursperei",
            [99] = "Fremdengebäude",
            [100] = "Pokémon-Pension",
            [101] = "Schleiede-Kaufhaus",
            [102] = "Spielhalle",
            [103] = "Fleetburg-Bibliothek",
            [104] = "Leuchtturm von Sonnewik",
            [105] = "Sonnewik-Markt",
            [106] = "Pokémon-Landgut",
            [107] = "Haus der Fußabdrücke",
            [108] = "Café",
            [109] = "Hotel Prachtsee",
            [110] = "Restaurant Sieben Sterne",
            [111] = "Kampfpark",
            [112] = "Kampfzone",
            [113] = "Kampffabrik",
            [114] = "Kampfpalais",
            [115] = "Kampfarkaden",
            [116] = "Kampfsaal",
            [117] = "Zerrwelt",
            [118] = "Global Terminal",
            [119] = "Villa",
            [120] = "Überlebensareal-Kampfhaus",
            [121] = "Rotoms Raum",
            [122] = "Galaktik-Gebäude Ewigenau",
            [123] = "Eisen-Ruinen",
            [124] = "Eisberg-Ruinen",
            [125] = "Felsen-Ruinen",
            [126] = "Starter",
            [127] = "Rosalia City",
            [128] = "Viola City",
            [129] = "Azalea City",
            [130] = "Anemonia City",
            [131] = "Dukatia City",
            [132] = "Oliviana City",
            [133] = "Teak City",
            [134] = "Mahagonia City",
            [135] = "See des Zorns",
            [136] = "Ebenholz City",
            [137] = "Silberberg",
            [138] = "Alabastia",
            [139] = "Vertania City",
            [140] = "Marmoria City",
            [141] = "Azuria City",
            [142] = "Lavandia",
            [143] = "Orania City",
            [144] = "Prismania City",
            [145] = "Fuchsania City",
            [146] = "Zinnoberinsel",
            [147] = "Indigo-Plateau",
            [148] = "Saffronia City",
            [197] = "Digdas Höhle",
            [198] = "Mondberg",
            [199] = "Azuria-Höhle",
            [200] = "Felstunnel",
            [201] = "Kraftwerk",
            [202] = "Safari-Zone",
            [203] = "Seeschauminseln",
            [204] = "Knofensaturm",
            [205] = "Glockenturm",
            [206] = "Ruinen von Teak City",
            [207] = "Nationalpark",
            [208] = "Radioturm",
            [209] = "Alph-Ruinen",
            [210] = "Einheitshöhle",
            [211] = "Flegmon-Brunnen",
            [212] = "Leuchtturm",
            [213] = "Rocket-Versteck",
            [214] = "Steineichenwald",
            [215] = "Dukatia-Tunnel",
            [216] = "Kesselberg",
            [217] = "Eispfad",
            [218] = "Strudelinseln",
            [219] = "Silberberghöhle",
            [220] = "Dunkelhöhle",
            [221] = "Siegesstraße (Kanto)",
            [222] = "Drachenhöhle",
            [223] = "Tohjo-Fälle",
            [224] = "Vertania-Wald",
            [225] = "Pokéathlon-Hallen",
            [226] = "M.S. Aqua",
            [227] = "Safari-Zonen-Eingang",
            [228] = "Felsenhöhle",
            [229] = "Zugang zur Kampfzone",
            [230] = "Glockenklangpfad",
            [231] = "Sinjoh-Ruinen",
            [232] = "Felsenherzturm",
            [233] = "Pokéwalker",
            [234] = "Felsklippentor",
            [2000] = "Pensionsleiter",
            [2001] = "Linktausch (erhalten)",
            [2002] = "Linktausch (getroffen)",
            [2003] = "Kanto",
            [2004] = "Johto",
            [2005] = "Hoenn",
            [2006] = "Sinnoh",
            [2007] = "Unbekannter Ort",
            [2008] = "Fernes Land",
            [2009] = "Reisender Mann",
            [2010] = "Urs",
            [2011] = "Cynthia",
            [2012] = "Mysteriöse Zone",
            [2013] = "Mr. Pokémon",
            [2014] = "Primo"
        };

        for (var id = 16; id <= 45; id++)
        {
            locations[id] = $"Route {201 + id - 16}";
        }

        for (var id = 149; id <= 176; id++)
        {
            locations[id] = $"Route {1 + id - 149}";
        }

        for (var id = 177; id <= 196; id++)
        {
            locations[id] = $"Route {29 + id - 177}";
        }

        return locations;
    }
}
